version: '3.1'

volumes:
  vol_geoserver:
  vol_zoatrack:
  vol_postgis:

services:
      
  dnsmasq:
    image: andyshinn/dnsmasq:2.76
    command: --log-facility=- --server=127.0.0.11 --server=193.10.57.11 --server=8.8.8.8 --server=172.16.0.72 --server=172.16.0.7 --neg-ttl=3600 --cache-size=1000 --max-cache-ttl=3600 --min-cache-ttl=3600 --all-servers
    cap_add: 
      - NET_ADMIN
    ports:
      - 172.17.0.1:53:53/tcp
      - 172.17.0.1:53:53/udp
    links:
      - proxy:zoa.bioatlas.se

  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

  web:
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=zoa.bioatlas.se
    volumes:
      - ./app.conf:/etc/nginx/conf.d/app.conf
#      - ./index.html:/usr/share/nginx/html/index.html
    depends_on:
      - zoatrack
      - geoserver

  postgis:
#    image: kartoza/postgis:9.4-2.1
    image: kartoza/postgis:9.3-2.1
    env_file: .env
#    command: postgres -c listen_addresses='*'
#    volumes:
#      - ./pg_hba.conf:/etc/postgresql/9.3/main/pg_hba.conf

  geoserver:
    image: kartoza/geoserver:2.8.0
    env_file: .env
    volumes:
      - vol_geoserver:/opt/geoserver/data_dir

  zoatrack:
    image: bioatlas/zoatrack:latest
    volumes:
      - vol_zoatrack:/var/local/oztrack
      - ./zoatrack.properties:/var/local/oztrack/custom.properties
    env_file: .env
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true -Dorg.oztrack.conf.customConfigFile=/var/local/oztrack/custom.properties
    depends_on:
      - geoserver
      - postgis
